application: tiny-ci
version: last
runtime: python27
api_version: 1
threadsafe: yes
module: default

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/.*
  script: tinyciapi.main.app

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- test/.*
- cmds/.*
